#
# Copyright (c) 2018 Seavus. All Rights Reserved.
#
# Use of this source code is governed by an MIT license, included in 'LICENSE.Seavus'.
#

spring:
  application:
    name: api-gateway-cqrs
  profiles:
    active: api-gateway.cqrs

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}