#
# Copyright (c) 2018 Seavus. All Rights Reserved.
#
# Use of this source code is governed by an MIT license, included in 'LICENSE.Seavus'.
#

spring:
  application:
    name: book-catalog

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}